sudo: false
language: ruby
cache:
  bundler: true
addons:
  postgresql: "9.3"
rvm:
  - 2.3.0
notifications:
  email: false

before_script:
  - bundle exec rake db:create db:schema:load RAILS_ENV=test
script:
  - xvfb-run bundle exec rspec --format progress
  - /bin/bash build_scripts/gh-publisher.sh

